sudo: false
cache: pip
language: python
python:
- '3.6'

install:
    - pip install tox-travis
    - pip install codecov

script:
    - travis-sphinx build
    
after_success:
    - travis-sphinx deploy
