sudo: false
language: python - "2.7"

install:
    - pip install --user travis-sphinx
    - export PATH=$HOME/.local/bin:$PATH
    - pip install sphinx sphinx-autobuild
    - pip install --user sphinx_rtd_theme

script:
    - travis-sphinx build --nowarn
    
after_success:
    - travis-sphinx deploy
